management:
  security:
    enable: true

    
spring:
  resources:
    chain:
      enabled: true
jwt:
  header: Authorization
  expires_in: 6 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN
  
app:
  name: assignment